package: manage_sql
version: '1.0.0-alpha1'
author: Your Name
supportpage: https://github.com/your/repo

requires:
    php: '>=8.1'
    redaxo: '>=5.18.1'
    packages:
        yform: '>=4.0.0'

page:
    title: 'manage_sql'
    perm: admin
    icon: rex-icon fa-server
    subpages:
        tables: 
            title: 'Tabellen'
            icon: rex-icon fa-table
        create:
            title: 'Neue Tabelle'
            icon: rex-icon fa-plus
            itemclass: pull-right
        query:
            title: 'Query Builder'
            icon: rex-icon fa-database
        yorm:
            title: 'YORM Generator'
            icon: rex-icon fa-code
        sql:
            title: 'REX SQLTable'
            icon: rex-icon fa-code
            itemclass: pull-right
        view:
            title: 'View Builder'
            icon: rex-icon fa-eye
        join:
            title: 'JOIN Builder'
            icon: rex-icon fa-link
        edit:
            title: 'Tabelle bearbeiten'
            icon: rex-icon fa-edit
            hidden: true
        records:
            title: 'Data Manager'
            icon: rex-icon fa-table-cells
