package: table_builder
version: '1.0.0'
author: Your Name
supportpage: https://github.com/your/repo

requires:
    php: '>=8.1'
    redaxo: '>=5.18.1'

page:
    title: 'Table Builder'
    perm: admin
    icon: rex-icon fa-table

pages:
    tables:
        title: 'Tabellen'
        icon: rex-icon fa-table
        path: pages/tables.php
    create:
        title: 'Neue Tabelle'
        icon: rex-icon fa-plus
        itemclass: pull-right
        path: pages/create.php
    sql:
        title: 'SQL Export'
        icon: rex-icon fa-code
        itemclass: pull-right
        path: pages/sql.php
    edit:
        title: 'Tabelle bearbeiten'
        path: pages/edit.php
        hidden: true

default_config:
    table_prefix: 'rex_'
