package: table_builder
version: '1.0.0'
author: Your Name
supportpage: https://github.com/your/repo

requires:
    php: '>=8.1'
    redaxo: '>=5.18.1'
    packages:
        yform: '>=4.0.0'

page:
    title: 'Table Builder'
    perm: admin
    icon: rex-icon fa-table
    subpages:
        tables: 
            title: 'Tabellen'
            icon: rex-icon fa-table
        create:
            title: 'Neue Tabelle'
            icon: rex-icon fa-plus
            itemclass: pull-right
        query:
            title: 'Query Builder'
            icon: rex-icon fa-database
        yorm:
            title: 'YORM Generator'
            icon: rex-icon fa-code
        sql:
            title: 'SQL Export'
            icon: rex-icon fa-code
            itemclass: pull-right
        edit:
            title: 'Tabelle bearbeiten'
            icon: rex-icon fa-edit
            hidden: true
        data:
            title: 'Hausmeister'
            icon: rex-icon fa-edit
